name: tempo_learn
description: Tempo Learn.
publish_to: 'Play Store'
version: 0.1.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.4
  flutter_svg: ^2.0.7
  stroke_text: ^0.0.2
  video_player: ^2.8.1
  chewie: ^1.7.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/ic_launcher_rounded_square.png"
  adaptive_icon_bacground: "#ffffff"
  adaptive_icon_foreground: "assets/icons/ic_launcher_rounded_square.png"

flutter_native_splash:
  android: false
  ios: false
  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/icons/
  fonts:
    - family: EduTAS
      fonts:
        - asset: assets/fonts/EduTAS/EduTAS-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
